FIX: Review mode. RFT: Better script layout.

diff --git a/tools/clang-format-all b/tools/clang-format-all
--- a/tools/clang-format-all
+++ b/tools/clang-format-all
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# TODO: Fix review mode for when there are no differences.
-
 FIX_MODE=0
 REVIEW_MODE=0
 SIMULATE_MODE=0
@@ -19,58 +17,70 @@ function showHelpAndQuit()
   exit 1
 }
 
-if [ $# -eq 1 ]
-then
-  if [[ "$1" == "fix" ]]
+function parseCommandline()
+{
+  if [ $# -eq 1 ]
   then
-    FIX_MODE=1
-  elif [[ "$1" == "review" ]]
-  then
-    REVIEW_MODE=1
-  elif [[ "$1" == "simulate" ]]
-  then
-    SIMULATE_MODE=1
+    if [[ "$1" == "fix" ]]
+    then
+      FIX_MODE=1
+    elif [[ "$1" == "review" ]]
+    then
+      REVIEW_MODE=1
+    elif [[ "$1" == "simulate" ]]
+    then
+      SIMULATE_MODE=1
+    else
+      showHelpAndQuit
+    fi
   else
     showHelpAndQuit
   fi
-else
-  showHelpAndQuit
-fi
+}
 
-if [ ! -f ./.clang-format ]
-then
-  >&2 echo "No .clang-format file found in this directory, aborting."
-  exit 1
-fi
+function checkForConfigurationFile()
+{
+  if [ ! -f ./.clang-format ]
+  then
+    >&2 echo "No .clang-format file found in this directory, aborting."
+    exit 1
+  fi
+}
 
-FILE_LIST=$(mktemp)
-find src/ -type f -name "*.[ch]pp"   >  ${FILE_LIST}
-find tests/ -type f -name "*.[ch]pp" >> ${FILE_LIST}
+function runClangFormat()
+{
+  FILE_LIST=$(mktemp)
+  find src/ -type f -name "*.[ch]pp"   >  ${FILE_LIST}
+  find tests/ -type f -name "*.[ch]pp" >> ${FILE_LIST}
+  
+  if [ ${FIX_MODE} -eq 1 ]
+  then
+    while read line
+    do
+      clang-format -i ${line}
+    done < ${FILE_LIST}
+  elif [ ${REVIEW_MODE} -eq 1 ]
+  then
+    while read line
+    do
+      if [ ! -z "$(clang-format ${line} | diff -u --from-file=${line} -)" ]
+      then
+        clang-format ${line} | diff -u --from-file=${line} - | view -
+      fi
+    done < ${FILE_LIST}
+  elif [ ${SIMULATE_MODE} -eq 1 ]
+  then
+    while read line
+    do
+      clang-format ${line} | diff -u --from-file=${line} -
+    done < ${FILE_LIST}
+  fi
+  
+  rm -f ${FILE_LIST}
+}
 
-
-if [ ${FIX_MODE} -eq 1 ]
-then
-  while read line
-  do
-    clang-format -i ${line}
-  done < ${FILE_LIST}
-elif [ ${REVIEW_MODE} -eq 1 ]
-then
-  while read line
-  do
-    if [ -n "$(clang-format-6.0 ${line} | diff -u - <(cat ${line}) | grep -v '^$')" ]
-    then
-      clang-format ${line} | diff -u --from-file=${line} - | view -
-    fi
-  done < ${FILE_LIST}
-elif [ ${SIMULATE_MODE} -eq 1 ]
-then
-  while read line
-  do
-    clang-format ${line} | diff -u --from-file=${line} -
-  done < ${FILE_LIST}
-fi
-
-rm -f ${FILE_LIST}
+parseCommandline $@
+checkForConfigurationFile
+runClangFormat
 
 exit 0
